source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "rack-cors"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 8.0"
gem "web-push", "~> 3.0"
gem "anthropic", "~> 0.3"
gem "image_processing", "~> 1.13"
gem "connection_pool", "~> 2.4"
gem "ruby-openai"
gem "dotenv-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "simplecov", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "shoulda-matchers", "~> 6.0"
  gem "webmock", "~> 3.23"
  gem "vcr", "~> 6.3"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
